services:
  - type: web
    name: tweelyzer-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BEARER_TOKEN
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
